# Generated by Django 3.0.5 on 2020-04-02 06:17

from django.db import migrations, models
import django.db.models.deletion
import main.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Party',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default=main.models.generate_code, editable=False, max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='Suggestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media_id', models.IntegerField()),
                ('media_type', models.CharField(choices=[('movie', 'Movie'), ('tv', 'TV show')], max_length=5)),
                ('party', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Party')),
            ],
            options={
                'unique_together': {('party', 'media_id', 'media_type')},
            },
        ),
    ]
