# Generated by Django 3.0.5 on 2020-04-02 02:22

from django.db import migrations, models


def insert_message(apps, schema_editor):
    Message = apps.get_model('main', 'Message')
    Message.objects.create(message="Hello, Django!")


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
            ],
        ),
        migrations.RunPython(insert_message),
    ]
