# Generated by Django 3.0.5 on 2020-04-03 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sessions', '0001_initial'),
        ('main', '0002_auto_20200402_2128'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='vote',
            unique_together={('session', 'suggestion', 'value')},
        ),
    ]
